### ISSUE TITLE
一直觉得vuex和redux的写法很傻逼，终于看到有人和我一样想了

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [guyskk/hami-vuex#1]

**Comment by guyskk** [comment]
哈哈，估计是历史原因吧，都从Flux学来的。

> Redux combines the ideas from Flux, [Command pattern](https://www.wikiwand.com/en/Command_pattern) and [Elm architecture](https://guide.elm-lang.org/architecture/)
> --- [Flux](https://facebook.github.io/flux/docs/related-libraries#redux---alternative-state-management)
